#!/bin/bash

echo " "
echo "************ Problem 5.A"
echo " "
# code your solution to problem A of Part 5 below this line

echo " "
echo "************ Problem 5.B"
echo " "
# code your solution to problem B of Part 5 below this line
